server:
  port: 9002

spring:
  application:
    name: service-auth

  profiles:
    include: common_prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

  instance:
    instance-id: 授权服务-9002
    prefer-ip-address: true

info:
  author.name: trevor
  app.name: general
  server.port: ${server.port}
  application.name: ${spring.application.name}
